name: Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0

      - name: Run tests and generate coverage report
        run: ./gradlew koverXmlReport -x :chat:testReleaseUnitTest

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@5f58465b6f395c8fa3adc2665e27250bad87de50 # v1
        with:
          path: |
            ${{ github.workspace }}/chat/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          coverage-counter-type: LINE
