name: API Reference
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    if: github.actor != 'dependabot[bot]' || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          persist-credentials: false

      - name: Set up Java 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
        with:
          cache-disabled: true

      - name: Build Documentation
        run: ./gradlew dokkaHtml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.ABLY_AWS_ACCOUNT_ID_SDK }}:role/ably-sdk-builds-ably-chat-kotlin
          role-session-name: "${{ github.run_id }}-${{ github.run_number }}"

      - name: Upload Documentation
        uses: ably/sdk-upload-action@4e694297f208b72b5a9f6b1248a1556f19f821d6 # v2.2.0
        with:
          sourcePath: chat/build/dokka/html
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: dokka
